trigger:
  branches:
    include:
      - master
      - develop

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  sqlConnectionString: $(SqlConnectionString)

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.303'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet build devops.sln --configuration $(buildConfiguration)
  displayName: 'Build solution'

- script: |
    dotnet publish devops.sln --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish project'

- script: |
    echo {
      "IsEncrypted": false,
      "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=true",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet",
        "SqlConnectionString": "$(sqlConnectionString)"
      }
    } > $(Build.ArtifactStagingDirectory)/local.settings.json
  displayName: 'Create local.settings.json'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive files'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'
